### ISSUE TITLE
增加 ASN 131495

### ISSUE THREAD

**Issue by MOOnLyer** [VirgilClyne/GetSomeFries#34]
建议增加 131495
以解决 link.zhihu.com 不直连的问题

**Comment by VirgilClyne** [comment]
一直都有啊

**Comment by MOOnLyer** [comment]
> 一直都有啊

在 [ASN China](https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/auto-update/ruleset/ASN.China.list) 这里面没有搜到的 只有看到 AS 131497

另外美团的 AS 63619 也不在其中

**Comment by VirgilClyne** [comment]
> > 一直都有啊
> 
> 在 [ASN China](https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/auto-update/ruleset/ASN.China.list) 这里面没有搜到的 只有看到 AS 131497
> 
> 另外美团的 AS 63619 也不在其中

自动版啊 明白了

**Comment by MOOnLyer** [comment]
> > > 一直都有啊
> > 
> > 
> > 在 [ASN China](https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/auto-update/ruleset/ASN.China.list) 这里面没有搜到的 只有看到 AS 131497
> > 另外美团的 AS 63619 也不在其中
> 
> 自动版啊 明白了

这是不是意味着用主分支里的 要稳定一些？
