### ISSUE TITLE
Quantumult X的HTTPDNS规则似乎存在问题

### ISSUE THREAD

**Issue by svngxr** [VirgilClyne/GetSomeFries#44]
https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/ruleset/HTTPDNS.Block.list
Quantumult X中应该是用host而不是DOMAIN，请考虑修改一下

**Comment by svngxr** [comment]
补充
Quantumult X应该使用IP6-CIDR而不是IP-CIDR6

**Comment by VirgilClyne** [comment]
QX的语法特殊，请配合`资源解析器`使用
