### ISSUE TITLE
ntp 服务有必要直连吗？

### ISSUE THREAD

**Issue by OVOJKzzZ** [VirgilClyne/GetSomeFries#58]
直连和走代理有什么区别？难不成走代理就无法同步时间了吗？或同步不准？

**Comment by VirgilClyne** [comment]
https://zh.wikipedia.org/wiki/%E7%B6%B2%E8%B7%AF%E6%99%82%E9%96%93%E5%8D%94%E5%AE%9A

**Comment by OVOJKzzZ** [comment]
> https://zh.wikipedia.org/wiki/%E7%B6%B2%E8%B7%AF%E6%99%82%E9%96%93%E5%8D%94%E5%AE%9A

我没有问 ntp 是什么啊，我问的走代理和不走代理，不审题的吗

**Comment by VirgilClyne** [comment]
> > https://zh.wikipedia.org/wiki/%E7%B6%B2%E8%B7%AF%E6%99%82%E9%96%93%E5%8D%94%E5%AE%9A
> 
> 我没有问 ntp 是什么啊，我问的走代理和不走代理，不审题的吗

NTP通常可以在公共[互联网](https://zh.wikipedia.org/wiki/%E4%BA%92%E8%81%94%E7%BD%91)保持几十毫秒的误差，并且在理想的[局域网](https://zh.wikipedia.org/wiki/%E5%B1%80%E5%9F%9F%E7%BD%91)环境中可以实现超过1毫秒的精度。不对称[路由](https://zh.wikipedia.org/wiki/%E8%B7%AF%E7%94%B1)和[拥塞控制](https://zh.wikipedia.org/wiki/%E6%8B%A5%E5%A1%9E%E6%8E%A7%E5%88%B6)可能导致100毫秒（或更高）的误差。[[2]](https://zh.wikipedia.org/wiki/%E7%B6%B2%E8%B7%AF%E6%99%82%E9%96%93%E5%8D%94%E5%AE%9A#cite_note-summary-2)[[3]](https://zh.wikipedia.org/wiki/%E7%B6%B2%E8%B7%AF%E6%99%82%E9%96%93%E5%8D%94%E5%AE%9A#cite_note-faq-3)

**Comment by VirgilClyne** [comment]
> > > https://zh.wikipedia.org/wiki/%E7%B6%B2%E8%B7%AF%E6%99%82%E9%96%93%E5%8D%94%E5%AE%9A
> > 
> > 
> > 我没有问 ntp 是什么啊，我问的走代理和不走代理，不审题的吗
> 
> NTP通常可以在公共[互联网](https://zh.wikipedia.org/wiki/%E4%BA%92%E8%81%94%E7%BD%91)保持几十毫秒的误差，并且在理想的[局域网](https://zh.wikipedia.org/wiki/%E5%B1%80%E5%9F%9F%E7%BD%91)环境中可以实现超过1毫秒的精度。不对称[路由](https://zh.wikipedia.org/wiki/%E8%B7%AF%E7%94%B1)和[拥塞控制](https://zh.wikipedia.org/wiki/%E6%8B%A5%E5%A1%9E%E6%8E%A7%E5%88%B6)可能导致100毫秒（或更高）的误差。[[2]](https://zh.wikipedia.org/wiki/%E7%B6%B2%E8%B7%AF%E6%99%82%E9%96%93%E5%8D%94%E5%AE%9A#cite_note-summary-2)[[3]](https://zh.wikipedia.org/wiki/%E7%B6%B2%E8%B7%AF%E6%99%82%E9%96%93%E5%8D%94%E5%AE%9A#cite_note-faq-3)

refer [[3]](https://zh.wikipedia.org/wiki/%E7%B6%B2%E8%B7%AF%E6%99%82%E9%96%93%E5%8D%94%E5%AE%9A#cite_note-faq-3)
`A time difference of less than 128ms between server and client is required to maintain NTP synchronization. The typical accuracy on the Internet ranges from about 5ms to 100ms, possibly varying with network delays. A survey by Professor David L. Mills suggests that 90% of the NTP servers have network delays below 100ms, and about 99% are synchronized within one second to the synchronization peer.`

**Comment by OVOJKzzZ** [comment]
> > > https://zh.wikipedia.org/wiki/%E7%B6%B2%E8%B7%AF%E6%99%82%E9%96%93%E5%8D%94%E5%AE%9A
> > 
> > 
> > 我没有问 ntp 是什么啊，我问的走代理和不走代理，不审题的吗
> 
> NTP通常可以在公共[互联网](https://zh.wikipedia.org/wiki/%E4%BA%92%E8%81%94%E7%BD%91)保持几十毫秒的误差，并且在理想的[局域网](https://zh.wikipedia.org/wiki/%E5%B1%80%E5%9F%9F%E7%BD%91)环境中可以实现超过1毫秒的精度。不对称[路由](https://zh.wikipedia.org/wiki/%E8%B7%AF%E7%94%B1)和[拥塞控制](https://zh.wikipedia.org/wiki/%E6%8B%A5%E5%A1%9E%E6%8E%A7%E5%88%B6)可能导致100毫秒（或更高）的误差。[[2]](https://zh.wikipedia.org/wiki/%E7%B6%B2%E8%B7%AF%E6%99%82%E9%96%93%E5%8D%94%E5%AE%9A#cite_note-summary-2)[[3]](https://zh.wikipedia.org/wiki/%E7%B6%B2%E8%B7%AF%E6%99%82%E9%96%93%E5%8D%94%E5%AE%9A#cite_note-faq-3)

谢谢解答，代理增加延迟是必然的，先不说超远路由到国外，就光是加密解密就需要一定的耗时。这影响对于我来说，ntp 服务好像没有必要走直连？

**Comment by OVOJKzzZ** [comment]
> > > https://zh.wikipedia.org/wiki/%E7%B6%B2%E8%B7%AF%E6%99%82%E9%96%93%E5%8D%94%E5%AE%9A
> > 
> > 
> > 我没有问 ntp 是什么啊，我问的走代理和不走代理，不审题的吗
> 
> NTP通常可以在公共[互联网](https://zh.wikipedia.org/wiki/%E4%BA%92%E8%81%94%E7%BD%91)保持几十毫秒的误差，并且在理想的[局域网](https://zh.wikipedia.org/wiki/%E5%B1%80%E5%9F%9F%E7%BD%91)环境中可以实现超过1毫秒的精度。不对称[路由](https://zh.wikipedia.org/wiki/%E8%B7%AF%E7%94%B1)和[拥塞控制](https://zh.wikipedia.org/wiki/%E6%8B%A5%E5%A1%9E%E6%8E%A7%E5%88%B6)可能导致100毫秒（或更高）的误差。[[2]](https://zh.wikipedia.org/wiki/%E7%B6%B2%E8%B7%AF%E6%99%82%E9%96%93%E5%8D%94%E5%AE%9A#cite_note-summary-2)[[3]](https://zh.wikipedia.org/wiki/%E7%B6%B2%E8%B7%AF%E6%99%82%E9%96%93%E5%8D%94%E5%AE%9A#cite_note-faq-3)

ntp 服务走直连了，那是不是可以通过 ntp 服务来泄漏你的源/真实 ip 呢？
