### ISSUE TITLE
Telegram讨论组群组机器人是不是有误封

### ISSUE THREAD

**Issue by Saszr** [VirgilClyne/GetSomeFries#7]
抱歉，提了个和项目没有关联的 issue
主要是 Telegram 讨论组没有反馈渠道
进讨论组发现没有什么验证，直接是被禁言状态，然后问了问其他新进入的成员也是这个状态
是有什么群组规则么，还是群组机器人误封
因为看了 Stash 的群发现有误封的情况
<img width="438" alt="image" src="https://user-images.githubusercontent.com/22406550/164877982-4c90dccb-4d4b-42c7-b018-033c34f797ff.png">

**Comment by VirgilClyne** [comment]
是的，似乎昨天开始出现的，我会定时检查列表解除禁言状态
