### ISSUE TITLE
使用ASN分流后，还需要用域名规则么？

### ISSUE THREAD

**Issue by woyin** [VirgilClyne/GetSomeFries#72]
使用了大佬的ASN China之后，我就只针对国外流媒体等进行了分流，其他的都交给了兜底规则。
但是我有个疑惑：
针对阿里、腾讯、以及各个视频网站而言，他们在国外也提供的相同的服务情况下，会不会因为DNS解析到国外，导致ASN China无法涵盖相关IP，导致这些网站（比如B站、优酷、腾讯视频等）走的是代理，而不是走DIRECT规则？

**Comment by VirgilClyne** [comment]
ASN China 没时间维护
建议使用
https://github.com/SukkaW/Surge/?tab=readme-ov-file#chnroute-cidr

**Comment by woyin** [comment]
感谢回复。
